# Generated by Django 3.2.7 on 2021-12-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_auto_20211207_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_caption',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
